### ISSUE TITLE
Simulate lot of clients : shared executor for connectors

### ISSUE THREAD

**Issue by sbernard31** [eclipse-californium/californium#1203]
If you want to simulates a lot of coap peers on the same VM with default configuration you will consume a lot of Java Threads.

With : 
 - `coapServer.setExecutors(sharedExecutor, sharedExecutor, true);`
 -  `dtlsConnector.setExecutor(sharedExecutor);` 

you can share lot of them and reduce drastically the number of  threads needed.

But you will still need some dedicate threads by peer's connectors : 
 - 2 threads (receiver/sender) for UDP connector,
 -  1 thread (received) for DTLS connector.

Meaning if you simulate 3000 peers(using only 1 connector) with 100 threads in your shared executor, you will consume `3000*2+100= 6100` threads for UDP or `3000*1+100= 3100` for DTLS.

A solution could be to implement 2 more NIO based connectors. (https://github.com/eclipse/californium/issues/936#issuecomment-494076915)

**Comment by sbernard31** [comment]
(@boaks  I know we only discuss about that, and I agree this is not a priority, I just open this ticket to be able to reference it)

**Comment by boaks** [comment]
Just to mention: for DTLS you may use the sharedExecutor also for so only 1 additional receiver thread will be required per client.

**Comment by boaks** [comment]
At least on unix 10000 clients run, but require some adaption in the environment.

[benchmark.sh](https://github.com/eclipse/californium/blob/master/demo-apps/cf-extplugtest-client/benchmark.sh#L28)

**Comment by sbernard31** [comment]
> for DTLS you may use the sharedExecutor also, so only 1 additional receiver thread will be required per client.

Thx for the clarification, I fix the issue description and change the Leshan code to limit to 1 receiver for client.

**Comment by boaks** [comment]
I would like to close this one.
See PR #2096

**Comment by boaks** [comment]
Hibernating.

**Comment by boaks** [comment]
PR #2096 contains a shot explanation.

I consider, that issues without progress are better marked with "hibernate".
The section [contributing](https://github.com/eclipse-californium/californium#contributing) contains the a link to the list.

**Comment by sbernard31** [comment]
I can understanf the `hibernate` tag to help to find it.
I just don't understand why closing it ?

**Comment by boaks** [comment]
In my opinion, that sharps the focus for the ongoing "issues".
Even, if for now, that's not really strict. There are also a couple of aged issues, also without progress, which are still open.
If you prefer to reopen it, please do so. I didn't get a reaction marking it with "could this be closed?", so I assumed it's OK.

**Comment by sbernard31** [comment]
>  If you prefer to reopen it, please do so. I didn't get a reaction marking it with "could this be closed?", so I assumed it's OK.

My remarks is not specific to this issue, this was more a generics one.
Closing an issue reduces its visibility, not sure this is the right way if you want to get more feedback/contribution about it. 

Anyway, if you thing it's fine like this.
