### ISSUE TITLE
Experimenting coap+tcp 

### ISSUE THREAD

**Issue by sbernard31** [eclipse-californium/californium#2081]
I'm experiment to add coap+tcp support to Leshan : https://github.com/eclipse/leshan/pull/1312

And I  face some issue which could come from my lack of knowledge of netty and TCP in a general way.

In my first test I face some : 
```
org.eclipse.leshan.core.request.exception.UnconnectedPeerException: Unable to send request coap://127.0.0.1:56124/3/0 : peer is not connected
	at org.eclipse.leshan.core.californium.DefaultExceptionTranslator.translate(DefaultExceptionTranslator.java:28)
	at org.eclipse.leshan.core.californium.CoapSyncRequestObserver.onSendError(CoapSyncRequestObserver.java:100)
	at org.eclipse.californium.core.coap.Message.setSendError(Message.java:1029)
	at org.eclipse.californium.core.coap.Request.setSendError(Request.java:1032)
	at org.eclipse.californium.core.network.CoapEndpoint$SendingCallback.onError(CoapEndpoint.java:1299)
	at org.eclipse.californium.elements.RawData.onError(RawData.java:314)
	at org.eclipse.californium.elements.tcp.netty.TcpServerConnector.send(TcpServerConnector.java:200)
	at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendRequest(CoapEndpoint.java:924)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendRequest(BaseCoapStack.java:231)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendRequest(BlockwiseLayer.java:498)
	at org.eclipse.californium.core.network.stack.TcpObserveLayer.sendRequest(TcpObserveLayer.java:57)
	at org.eclipse.californium.core.network.stack.AbstractLayer.sendRequest(AbstractLayer.java:69)
	at org.eclipse.californium.core.network.stack.TcpExchangeCleanupLayer.sendRequest(TcpExchangeCleanupLayer.java:45)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendRequest(BaseCoapStack.java:188)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.sendRequest(BaseCoapStack.java:87)
	at org.eclipse.californium.core.network.CoapEndpoint$3.run(CoapEndpoint.java:701)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.californium.elements.exception.EndpointUnconnectedException: TCP client not connected!
	... 15 common frames omitted
```

Adding some logs in `TcpServerConnector`, I can see that channel become inactive after 10s : 
```
2022-10-27 18:21:18,875 TcpServerConnector   [WARN] active channel for /127.0.0.1:51216
2022-10-27 18:21:28,901 TcpServerConnector   [WARN] inactive channel for /127.0.0.1:51216
```

Then I see in TcpConfig, there is `TCP.CONNECTION_IDLE_TIMEOUT=10[s]` setting which allow to set [`IdleStateHandler.allIdleTime`](https://netty.io/4.1/api/io/netty/handler/timeout/IdleStateHandler.html).
I tested to change it  and this changes the activation duration to minimum value between CONNECTION_IDLE_TIMEOUT of client and  CONNECTION_IDLE_TIMEOUT of server. (is it the expected result ?)

I also see in the code : 
https://github.com/eclipse-californium/californium/blob/ae31ce7a8b366f558763a4f78b53478f4718bca6/element-connector-tcp-netty/src/main/java/org/eclipse/californium/elements/tcp/netty/TcpServerConnector.java#L194-L202

So I asking myself what is the right approach for LWM2M use case ?
- should I increase the connection idle timeout to something very large (I feel this is not the idea but I'm not sure)
- should we implement the //TODO above ? :point_up: 

Any advice is very welcomed :pray:

**Comment by sbernard31** [comment]
If needed I can give a LWM2M use case.

**Comment by boaks** [comment]
> should I increase the connection idle timeout to something very large (I feel this is not the idea but I'm not sure)

That depends on what you want to achieve. And what the experience then will be.
So, many server frameworks close the connection after an idle time. In some cases this is even done by the network environment, e.g. old load-balancer. So, if you like, test with large times. We may also check, to leave out the `IdleStateHandler` for e.g. TCP.CONNECTION_IDLE_TIMEOUT=0 and/or null. For me the point is more, that some need to test that in the "wild". And maybe with some device typical TCP implementations on the client side.

> should we implement the //TODO above ?

I guess, that doesn't work. In TCP it's only possible to connect the other peer, if that listen on such connects. For client this will mainly not work. Anyway, if you like, test it.
(The comment is from the initial contribution in 2016.)

**Comment by boaks** [comment]
One details from experiments with coap+tcp using Android phones.

if at all, session resumption works only with the jce, if the connection was proper closed. If it just breaks, then the jce sticks to a deprecated recommendation to block the session. Not sure, if this is still valid for the current version or BouncyCastle.

**Comment by sbernard31** [comment]
> if at all, session resumption works only with the jce, if the connection was proper closed. If it just breaks, then the jce sticks to a deprecated recommendation to block the session. Not sure, if this is still valid for the current version or BouncyCastle.

You talk about session resumption and bouncy castle. So this makes me think that maybe I was not clear.
So just in case, for now I just experiment `coap+tcp`,  not `coaps+tcp`.


> That depends on what you want to achieve. And what the experience then will be.

Ok I will try to explain what I understood until now.
I try to read LWM2M v1.1.x (and v1.2.x) specification about CoAP over TCP and didn't find too much specific  to TCP.

So my understanding is :  

### if you don't use Queue Mode** (and so probably no NAT involved and no changing IP) : 

I guess this is relevant :   

> _"The LwM2M Server expects that the LwM2M Client is reachable via the TCP binding at any time."_

(from [LWM2M-v1.1.1@core§6.2.1.2. Behaviour with Current Transport Binding and Modes](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-1-2-0-6212-Behaviour-with-Current-Transport-Binding-and-Modes)


1. The LWM2M Client send a Register Request
2. Then LWM2M server must be able to send Downlink Request to Client at any moment. (at least as long as the client maintain the registration alive)

Note that device should send Registration Update Request periodically to maintain the registration alive.
For UDP, I know some device use very long period (some time more than 1 days) 

### if you use Queue Mode** (and so maybe  NAT involved, changing IP or sleeping device) : 

> _"A typical Queue Mode sequence follows the following steps:_
> 
>   _The LwM2M Client registers to the LwM2M Server and requests the LwM2M Server to run in Queue mode by using the correct Binding value in the registration._
> 
>   _The LwM2M Client is recommended to use the CoAP MAX_TRANSMIT_WAIT parameter to set a timer for how long it shall stay awake since last sent message to the LwM2M Server. After MAX_TRANSMIT_WAIT seconds without any messages from the LwM2M Server, the LwM2M Client enters a sleep mode._
> 
>   _At some point in time the LwM2M Client wakes up again and transmits a registration update message. Note: During the time the LwM2M Client has been sleeping the IP address assigned to it may have been released and / or existing NAT bindings may have been released. If this is the case, then the client needs to re-run the TLS/DTLS handshake with the LwM2M Server since an IP address and/or port number change will destroy the existing security context. For performance and efficiency reasons it is RECOMMENDED to utilize the TLS/DTLS session resumption._
> 
>    _When the LwM2M Server receives a message from the Client, it determines whether any messages need to be sent to the LwM2M Client, as instructed by the application server."_

(from [LWM2M-v1.1.1@transport§6.5. Queue Mode Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-5-0-65-Queue-Mode-Operation))

That Queue Mode case, should fit pretty well with connection idle timeout. (even if CoAP MAX_TRANSMIT_WAIT seems to not really make sense for TCP)
I don't understand TCP enough but I guess with TCP we could use something more connected oriented to let know when we are awake or sleeping instead of timeout ? :thinking:

**Comment by boaks** [comment]
> So just in case, for now I just experiment coap+tcp, not coaps+tcp.

Ah sorry, I missed that. Without encryption, that will get easier.

**Comment by boaks** [comment]
> I don't understand TCP enough but I guess with TCP we could use something more connected oriented to let know when we are awake or sleeping instead of timeout ? thinking

The "connected state" is also based on exchanged messages. If the transport is lost (wires cut), the close of one peer doesn't reach the other and with that, the connections is "ghosted" (the other peer is not aware of the close). Therefore many probes the connection frequently by exchanging messages to ensure, that it is still alive.
I don't know, how often such "ghost connections" will occur,

**Comment by jvermillard** [comment]
In any TCP protocol, when you want to keep the connection alive, you have some heartbeat mechanism.
As for UDP, depending on the network configuration (NAT boxes, session timeout in the router, etc..), you need to send the heartbeat more or less frequently to keep the connection open.

Now, where it starts to be interesting, as always with OMA, is you have a keep-alive defined in CoAP over TCP: https://www.rfc-editor.org/rfc/rfc8323#section-3.4 so if you keep the TCP connection alive, then what does the registration update useful for? 

I suspect that one workflow to handle it in non-queue mode:
 - open the TCP connection and send a registration or a registration update
 - keep the TCP connection alive using the ping/pong CoAP messages (a bit like you do with the MQTT protocol)
 - send registration updates in the TCP session from time to time to keep the specification happy

Now for queue mode:
 - open the TCP connection and send a registration or a registration update
 - wait some time and disconnect
 - reconnect to update the registration on time 
 - etc

Seeing how LWM2M over HTTP was specified (in an unimplementable way), I suspect they specified something without a proper implementation (as often). 

Do we know some available implementations of LWM2M over CoAP TCP? Outside of Ioterop claiming their proprietary client support TCP (see https://github.com/IOTEROP/IOWA), I didn't find any publically available resources.

**Comment by boaks** [comment]
We may ask Hannes Tschofenig, if he knows a implementation.

**Comment by sbernard31** [comment]
> We may ask Hannes Tschofenig, if he knows a implementation.

I will try to dig deeper into this then I will probably try to ping some LWM2M guys about coap+tcp.

> when you want to keep the connection alive, you have some heartbeat mechanism.

Yep so its seems :
- [`Registration Update`](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-2-0-622-Update-Operation) could play this kind of role at **LWM2M** level
- [`CoAP ping`](https://www.rfc-editor.org/rfc/rfc8323#section-3.4) at **CoAP** level
- It seems there is also a [`TCP Keep-Alives`](https://datatracker.ietf.org/doc/html/rfc9293#section-3.8.4) at **TCP** level

I will read more about [TCP](https://datatracker.ietf.org/doc/html/rfc9293), [coap+tcp](https://www.rfc-editor.org/rfc/rfc8323) and probably [netty](https://netty.io/wiki/).

And also make more test with current californium implementation.

I will let you know what I find.

**Comment by jvermillard** [comment]
TPC Keep-Alive is an optional feature removed by some middleboxes, so it isn't easy to use it reliably over internet

**Comment by sbernard31** [comment]
> TCP Keep-Alive is an optional feature removed by some middleboxes, so it isn't easy to use it reliably over internet

Yep, it seems you're right about that.
My reading during my investigation :point_up:  let me think that it's more and more supported by middle-boxes.

**Comment by boaks** [comment]
> no "auto close idle connection feature" (TCP.CONNECTION_IDLE_TIMEOUT= 0[s]) for server and client.

Therefore the current implementation needs to be adapted, right?

> a more mature implementation need probably more than that.

Just to remind: 
Californium has only a experimental early implementation of RFC 8323. I even don't know the gap.

**Comment by sbernard31** [comment]
> Therefore the current implementation needs to be adapted, right?

My current tests show that using this  TCP.CONNECTION_IDLE_TIMEOUT= 0[s] is working for me.
That at very short term no need to modify it.
