### ISSUE TITLE
Adding DTLS sequence number to endpoint context

### ISSUE THREAD

**Issue by adamsero** [eclipse-californium/californium#2085]
Hi, in this issue I wanted to request adding a small feature to the existing endpoint context code. I'm currently working on a service for monitoring the quality of network traffic that reaches Leshan server. 

The service would benefit greatly if it could make use of the DTLS sequence number field in COAP message's endpoint context - it can be used to assure continuous traffic and easy detection of missing packets. 

Since Leshan uses Californium, I had to make changes to the source code here and I'm hoping you could integrate it. The changes can be seen [here](https://github.com/JaroslawLegierski/californium/compare/main...opl/dtls_sequence_number) - they're really small and hopefully not a big problem to integrate.

**Comment by boaks** [comment]
A PR will be welcome! 
There is already a valid ECA for your e-mail address, so a PR should be easy, or?

A first look:

Did you consider [KEY_PREFIX_NONE_CRITICAL](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L64-L68)?

For the CID, we distinguish between read and write, so maybe

```
KEY_PREFIX_NONE_CRITICAL + "DTLS_READ_SEQUENCE_NUMBER"
```

**Comment by boaks** [comment]
Just to mention:

There is also a [DatagramFilter](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/DatagramFilter.java), which may be also useful for analysis.

**Comment by adamsero** [comment]
> Did you consider [KEY_PREFIX_NONE_CRITICAL](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/MapBasedEndpointContext.java#L64-L68)?

Yes, I added that, thanks for noticing.

Created PR #2086 for this.

**Comment by boaks** [comment]
PR #2086 has been merged.
