### ISSUE TITLE
Data regarding dropped records in DTLSConnector

### ISSUE THREAD

**Issue by Wisien999** [eclipse-californium/californium#2099]
Hello,
I use Scandium as the DTLS server and I would like to know what exact record/datagram was dropped in `DTLSConnector` (or at least its source address/ConnectionID). Is there any existing mechanism which allows me to do so?

In case it currently is impossible to do this could we introduce such a functionality? Also, how would you inject it into the current implementation? I can add the PR with my suggested changes if needed.

**Comment by boaks** [comment]
At least for messages from "valid peer addresses/connection ids",
[DatagramFilter.onMacError(Record record, Connection connection)](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/DatagramFilter.java#L50) reports that.
If more is required, e.g. dropped messages from unknown sources, then the `DatagramFilter` must be extended. Usually, adding just a method/function fails, revapi will report that as semantic versioning error. We usually go then for something as `AdvancedDatagramFilter`and merge the interfaces again on the next major release.

**Comment by Wisien999** [comment]
Thank you for your response. Unfortunately, `DatagramFilter.onMacError(Record record, Connection connection)` won't work. I need to know every dropped datagram/record. So, more or less, in every place where `DtlsHealth.receivingRecord(true)` is called. Is something like this possible?

**Comment by boaks** [comment]
>  Is something like this possible?

Sure. I would prefer to have the `DatagramFilter` extended as described above.
Please be aware, that using resources (CPU/RAM) for "unverified peers" are pretty much in danger of DoS. So be very careful.

**Comment by Wisien999** [comment]
Thank you for your valuable advice and resources. 
What I can see records can be dropped in a lot of places. For example:
```java
DTLSConnector.processRecords(...) {
	...
	if (connection == null) {
		if (health != null) {
			health.receivingRecord(true);
		}
		...
	}
	...
}
```
or
```java
DTLSConnector.processRecords(...) {
	...
	if (record.getConnectionId() == null && !connection.equalsPeerAddress(record.getPeerAddress())) {
		if (health != null) {
			health.receivingRecord(true);
		}
		return;
	}
	...
}
```
or more.
The only common part of them I see is that `health.receivingRecord(true)` is called. That is why what I would like to do is change `DtlsHealth.receivingRecord(boolean drop)` to `DtlsHealth.receivingRecord(boolean drop, Record record)`. This would allow users to create much more specific statistics and perform actions based on `record` data. Could such change be introduced to californium? Of course as you mentioned it is not a minor change and would be implemented in some `AdvancedDtlsHealth` at first and merged to `DtlsHealth` with major version release.

Alternatively in order to not break backward compatibility
```
interface DtlsRecordListener {
	void beforeProcessing(Record record);
	void onDrop(Record record);
	void afterProcessing(Record record);
}
```
could be introduced.

**Comment by boaks** [comment]
> The only common part of them I see is that health.receivingRecord(true) is called.

Yes. Until now, these drops are only counted for an health overview.
I would prefer to not mix up the functions. If the address is relevant, please extend the `DatagramFilter`. 
That's a little more to type, but it's not too complicated. And you may just add calls, where `health.receivingRecord(true);` is called. If you want to have your own 
"health-filter-what-ever" implementation of both interfaces (health and filter), then pass that as argument for the health and the filter.

> DtlsRecordListener

if you want all dropped messages, then a 

boolean DatagramFilter.onDrop(DatagramPacket packet);
boolean DatagramFilter.onDrop(Record record);

seems for me the right place.

So, for now I don't get it, why you don't want to use the `DatagramFilter`. Maybe you can give me some additional  reasons as the one with the `health.receivingRecord(true)`?

**Comment by Wisien999** [comment]
I was a little confused at first but I have nothing against modifying `DatagramFilter`.  Created PR #2100, please see.

**Comment by boaks** [comment]
PR #2100 is merged.
