### ISSUE TITLE
Can californium support TLS_RSA_WITH_AES_128_CBC_SHA256？

### ISSUE THREAD

**Issue by david9312** [eclipse-californium/californium#2101]
Actually,some backward devices can not support ECDHE,can californium support TLS_RSA_WITH_AES_128_CBC_SHA256 or provide samples for guding me to finish base on californium？🙏🙏🙏

**Comment by boaks** [comment]
For DTLS or TLS?

For TLS Californium uses the cipher suites offered by the JCE. 

For DTLS Scandium implements the cipher suited bases on the cryptographic functions of the JCE.
Support for TLS_RSA_WITH_AES_128_CBC_SHA256 requires therefore to invest time in implementing and interoperability testing. Both RSA key exchange and AES_CBC have some known issues, so both are not recommended. In sum, I'm not sure, if that pays really off. I would rather try to get the devices updated.

**Comment by boaks** [comment]
Just as estimation:

Good JCE cryptographic knowledge as base, that extension should take about 2-4 days + 2 days for interoperability test. To start, analyze the `ECDHClientKeyExchange`, the `ECDHServerKeyExchange`, and the `EcdhSignedServerKeyExchange`. Implement the `RSAClientKeyExchange` and `RSAServerKeyExchange` accordingly. Extend the `CipherSuites`, `HandshakeMessage`, `ClientHandshaker` and `ServerHandshaker`. Maybe the one or other additional change is required.

Without good JCE cryptographic knowledge, I don't think, it will work.
