### ISSUE TITLE
Observe message type

### ISSUE THREAD

**Issue by rogierc** [eclipse-californium/californium#2106]
[rfc7641 - Observing Resources in the Constrained Application Protocol (CoAP)](https://www.rfc-editor.org/info/rfc7641) describes (amongst other) the messages a CoAP client has to send to Register, Reregister and Cancel an observe relation. It makes no statement about the messagetype of these requests, meaning Confirmable (CON) and Non-confirmable (NON) requests are both valid.

Californium supports both message types for registering. The message type of the given Request wil be used by the CoapClient::observe call.:
```
public CoapObserveRelation observe(Request request, CoapHandler handler) 
``` 
The application can choose sending the registration request CON or NON as is suitable for the application. However, the reregister() and sendCancelObserve() methods of ClientObserveRelation always use `Request.newGet()` . Therefore proactive cancel and reregister requests are always sent CON.

An improvement would be to give the application control over the messagetype of the reregistration and cancel requests when needed. Also a default behaviour that for reregistration and cancel the same messagetype will be used as previous registration request could be more  appropriate.

I've implemented this. Please review these [changes](https://github.com/eclipse-californium/californium/compare/main...rogierc:californium:observe_msg_type). I can issue a merge request if you like.

The change of default behaviour could have impact on existing use cases, but maybe the impact is minor. When the actual default behaviour is considered a bug, these changes may be seen as "backward compatible" and it could be released in a Cf 3 version. What's your opinion on this?

**Comment by boaks** [comment]
Just to mention:
NON in request will not change "too much". In the very most cases, the NON request reaches the server, and the NON response the client. Only in cases, where a message gets lost, the used messages will change.

Anyway, I will have a look at the changes tomorrow.

**Comment by boaks** [comment]
I failed to comment on that link. How could feedback provided there?

**Comment by boaks** [comment]
Just as proposal:

- use rather `isConfirmable` and `setConfirmable` than the `type`. 
- add `isConfirmable` and `setConfirmable` also to `ClientObserveRelation` and 
  delegate that to the kept current `request`.
- always use the confirmable type of that current `request` to create reregister or cancel requests.
  The only critical path seems to be `reregister`, when the current `request` is update (That should be
  not too hard to "sync" somehow.
- this obsoletes the added `proactiveCancel` and `reregister` with confirmable as parameter.

As I wrote above, I failed to comment on the "changes" link above. 
I don't get the benefit of that approach compared to a PR. Maybe you can help me?

**Comment by rogierc** [comment]
Thanks for reviewing!

> I don't get the benefit of that approach compared to a PR.

CONTRIBUTING states: _1. Consider to start with creating an issue on GitHub to discuss your plans and get the proper startup information._ This gave me the impression a PR out of the blue is not appreciated. I'm happy to issue a PR if that's preferred. Didn't mean to cause any inconvenience.

> Just as proposal: ...

Your suggestions make sense, but I'm wondering about one thing:

When `ClientObserveRelation::setConfirmable( boolean )`  does change `request`  before a `reregister` or `cancel` is sent, there may arrive notifications or responses in the meantime. When they get processed in the context of the altered `request` which doesn't exactly represents the  request that triggered them, could that cause undesirable effects?

A "long"  living lock on `request` to sync this is not the way to go, I imagine.

**Comment by boaks** [comment]
> This gave me the impression a PR out of the blue is not appreciated. I'm happy to issue a PR if that's preferred. Didn't mean to cause any inconvenience.

From my side, the point is more, that I don't recommend to invest a lot of time in coding without asking before. But once someone already spend the time to prepare code, I feel fine with a PR. It's more efficient to discus some topics.

> When ClientObserveRelation::setConfirmable( boolean ) does change 

I would assume, that this happens very rare. As I wrote, I don't think, there is a that large benefit in changing it.
If you like, then use an additional field for that. Though the request all share the same token, the processing will in my opinion anyway be somehow "undefined". At least without spending time in analyzing the combinations and verify, that this doesn't harm.

**Comment by rogierc** [comment]
> I don't think, there is a that large benefit in changing it.

True, it's not a paramaount feature. It's just not that logical that a NON observe registration is CON reregistered. Also the feature allowes for usage that is provisioned by the RFC. A NON cancel could make sense to reduce traffic. When it gets lost no resend is done, it in fact turns into a reactive cancel as fall back mechanism. 
And additionally the user API of the [Mule CoAP Connector](https://github.com/teslanet-nl/mule-coap-connector) can be designed somewhat more logical with this feature.

> But you may go for a solution with an additional field, the it doesn't require to sync (at least for on a first look)`

Changing the `request` object that is also present in `ObservationStore` seems a bit risky to me. I gave the additional field solution a go. See the PR #2108

**Comment by rogierc** [comment]
PR is merged. Issue is resolved.
