### ISSUE TITLE
CoAP Californium redirect

### ISSUE THREAD

**Issue by fprokopovich** [eclipse-californium/californium#2117]
Hello! 
I have a question.
Is there any way to set up a redirect on the Californium CoAP server? I want to set up a demo so that my messages that I send to the Californium local server are forwarded to an external endpoint.

**Comment by boaks** [comment]
You may check, if the [coap-cross-proxy](https://github.com/eclipse-californium/californium/tree/main/californium-proxy2) does the job. It receives coap messages and forwards them either as coap or http. 

[cf-proxy-demo](https://github.com/eclipse-californium/californium/tree/main/demo-apps/cf-proxy2) may help to see, how that is intended to work.

**Comment by boaks** [comment]
A IP forward may also work. [Wiki Load Balancer](https://github.com/eclipse-californium/californium/wiki/DTLS-1.2-connection-ID-based-load-balancer) shows some forward rules, but general, the documentation of  "iptables" should be considered. (I'm not able to provide support for such IP forwarding.)

**Comment by fprokopovich** [comment]
Okay thanks! I will try
