### ISSUE TITLE
Provide information if we performed abbreviated handshake

### ISSUE THREAD

**Issue by Kudyyy** [eclipse-californium/californium#2119]
Currently it is possible to retrieve some information from handshaker after connection is established using SessionListener but it is impossible(or I did not found a way of doing that) to retrieve information if we performed abbreviated or full handshake. We can check if instance of handshaker is a ResumingServerHandshaker but it can still fallback to standard handshake. What I would like to achieve is to get information(as a server) if client resumed session or performed full handshake. Is it possible to add such implementation and extend the ServerHandshaker so it will contain such information?

**Comment by boaks** [comment]
>  What I would like to achieve is to get information(as a server) if client resumed session or performed full handshake. 

Any reason, why you want this information?

You may try to compare the `DTLSSession.getCreationTime()` with the `DTLSContext.getLastHandshakeTime()`. I would assume, that if the handshake time is 5s or more newer, then the last handshake is an abbreviated one. But I never have tested that.

Otherwise we could add a flag/method to the `Handshaker` with that information.

**Comment by Kudyyy** [comment]
Thank you! I need that information to perform different types of cleanups on the server, it depends on fact if handshake is abbreviated.

**Comment by boaks** [comment]
>  different types of cleanups

But you don't want to tell more?

**Comment by Kudyyy** [comment]
It is possible to remove connection from ConnectionStore with or without removing session from cache. 
I map each connection to client and I want to perform cleanup of old connection for given client.
I am using custom ConnectionStore and SessionStore and I want to have possibility to decide if session should be removed depending on abbreviated handshake as session will remain the same in case of resumption.

**Comment by boaks** [comment]
It depends on the details, maybe [DTLS_REMOVE_STALE_DOUBLE_PRINCIPALS](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/config/DtlsConfig.java#L932-L944) gets already very close to what you want.

Generally, Californium keeps the connections until the store exceeds and then the oldest connection is removed, if it's already stale. The `DTLS_REMOVE_STALE_DOUBLE_PRINCIPALS` considers also this "stale time", but removes double connections from a principal, if that reaches the stale time, even if the store is not exceeded.

**Comment by boaks** [comment]
If possible, please check, if PR #2120 works for you.

**Comment by Kudyyy** [comment]
`DTLS_REMOVE_STALE_DOUBLE_PRINCIPALS` is not enough for me but the PR you provided is exactly what I have needed. Thank you!

**Comment by boaks** [comment]
You're welcome.
