### ISSUE TITLE
Active Observe Cancelation - version 3.8.0

### ISSUE THREAD

**Issue by noomio** [eclipse-californium/californium#2121]
Hi,

An edge device is observing a recourse with a max-age of 10 minutes. Once this expires the edge device actively tries to cancel the observe but I have noticed that it doesn't always appear on the logs even though the server has replied to the cancelation. I can see the log sometimes but mostly it doesn't appear. Also I noticed intermittently all the tokens that are stale then are cancelled.

For the cancellation I send the token, the options used when observe request happened and the endpoint.

// Send observe GET
The observe confirmation with token **0xCB** was returned

// Max-Age expired and the device will send a cancellation 
coap_client_worker -> observe lifetime expired
tx_observe_cancel -> tot_msg_len: 35 bytes, observe sequence mid 23650
coap_client_tx_cb -> msg: 0x2000E8E8, conn: 0x1000008C
coap_client_tx_cb -> sending 
coap msg: 2000F4D0
msg_id_num: 23650
msg_token: **0xCB**
msg code: 1
msg type: 0
conn: 0x1000008C
ip: XXX.XXX.XXX.XXX
local port: 54556
remote port: 5683
coap_client_tx_cb -> sent to XXX.XXX.XXX.XXX:5683
coap_recv ->
	msg_id:           23650
	msg_code:         67
	msg_token:        **CB**
	coap_status:      0
	content_format:   -1
	options_list_ptr: 2000F4D0
	payload_len: 1
	size1: 0
	size2: 0
	block number: 4294967295
	payload_len:      1
	payload:          
list_check_marked_for_remove_observe -> msg:2000E8E8, conn=1000008C remove /MYENDPOINT

// Send new observe request with token **0x25**
coap_observe_error_cb -> error: 1009
coap_observe_error_cb -> observe renew /MYENDPOINT
coap_client_send_request_new -> queue message
coap_client_send_request_new -> message queued new msg: 2000F5A0, msg: 2000F4D0
coap_client_send_request_new -> message request sent to worker
coap_client_worker -> msg: 0x2000F5A0
gethostname_cached -> local cached entry XXX.XXX.XXX.XXX, ttl=728836
coap_client_worker -> tot_msg_len: 34 bytes
coap_client_worker -> request 
msg_id_num: 48008
msg_state: 4
state: 0
conn: 0x1000008C
msg confirmable: 1
msg token: **25**
msg uri path: /MYENDPOINT
coap_client_tx_cb -> msg: 0x2000F5A0, conn: 0x1000008C
coap_client_tx_cb -> sending 
coap msg: 2000E9E0
msg_id_num: 48008
msg_token: 0x25
msg code: 1
msg type: 0
conn: 0x1000008C
ip: XXX.XXX.XXX.XXX
local port: 54556
remote port: 5683
coap_client_tx_cb -> sent to XXX.XXX.XXX.XXX:5683
coap_recv ->
	msg_id:           48008
	msg_code:         67
	msg_token:        **25**
	coap_status:      0
	content_format:   -1
	options_list_ptr: 2000EA10
	payload_len: 1
	size1: 0
	size2: 0
	block number: 4294967295
	payload_len:      1
	payload:          
coap_client_worker -> msg code: 67
coap_client_worker -> observe msg code: 67
list_add_observe -> observe max-age: 600, token: **0x25**
coap_client_worker -> added observe to list msg: 2000F5A0

Logs from server:

![image](https://user-images.githubusercontent.com/51944940/226766930-de4c30b8-d7f8-402b-a294-fbb5a2b5bee3.png)

Is there something that I send wrongly or can it be something on the server?

**Comment by boaks** [comment]
You're client isn't Californium, right?
And for some reasons, you can't provide a ip capture?

> An edge device is observing a recourse with a max-age of 10 minutes. Once this expires the edge device actively tries to cancel the observe but I have noticed that it doesn't always appear on the logs even though the server has replied to the cancelation. I can see the log sometimes but mostly it doesn't appear. Also I noticed intermittently all the tokens that are stale then are cancelled.

That happens all on the client?

> Once this expires the edge device actively tries to cancel 

Looks more, that the device cancels the old observe and establish a new one. It's much easier to just "reregister" the observation, if "max-age" times out.

[RFC7641 - 3.3.1 - Freshness](https://www.rfc-editor.org/rfc/rfc7641#section-3.3.1)

> To make sure it has a current representation and/or to re-register
>    its interest in a resource, a client MAY issue a new GET request with
>    the same token as the original at any time.


> I can see the log sometimes but mostly it doesn't appear.

I'm not sure, what you client implementation does. Maybe it removes the old observe request when it sends the new. That may cause a race condition for the cancel response, which may be ignored when the old token is removed.

> Is there something that I send wrongly or can it be something on the server?

That's hard to see without capture. I'm not even sure, if I understand, what you want to achieve and what you exactly send and receive. Though Observe/Notify reuses the token, the messages may sometimes "crossing over" and don't match the expectations. For the most other traffic, the token is unique and makes the client side processing easy, for observe/notify and multicast this is not the case. 

>  or can it be something on the server?
  
:-) :-) :-) No, Californium is never wrong :-) :-) :-) .

**Comment by noomio** [comment]
Hi,

Client is on MCU with limited resources. LWIP + some parsing lib coap.

I keep track of observe and remove it from the list once it expires. I used to generate a new token when sending a new observe so maybe that wasn't right. 

I have now a fixed token when observing again and removed the active cancellation.

I think that it might be the implementation on the server side when its talking to rabbitmq. When I observe the /clock resource it works fine...

I will try and use your client whilst testing.

**Comment by boaks** [comment]
> I also noticed that the port number remains the same whereas in our resource it keeps changing so I think it's the implementation on our endpoint...

Yes, the observe registration is a combination of the resource-path, some options, and the remote endpoint (ip-address + port). In my experience, there are two cases, where a endpoint changes the ip-address + port:

- the peer reopens the UDP socket using the ephemeral port (mainly 0, which gets mapped to a free random port). That technique is intended for "short-living-communication", but "observe/notify is rather long-living-communiation". Just don't close the socket while the observation is ongoing.

- a NAT is changing the mapping and so the ip-address + port visible to the other peer is changing. Usually, the NAT is on the route from the device to the cloud-server. The NAT is not only changing the device's address after a quiet period, it will also block the traffic from the cloud-server to the device after that quiet period. The nasty point here is, that you usually not able to configure the NATs timeouts. Even the timeout itself is frequently not known, it's just assumed, that's about 30s to 100s. But the actual timeout may be different. You may overcome that by sending frequently messages. But that comes with data-volume and energy consumption. RFC7641 only works, if the IP routes works as well. With NATs that's frequently not the case.

**Comment by noomio** [comment]
Hi,

I maintain the same UDP and dont destroy it for each new observation.
This is connected via LTE so maybe its the NAT from the mobile provider?

I will try and ping from coap to verify this.

**Comment by boaks** [comment]
> This is connected via LTE so maybe its the NAT from the mobile provider?

Depends ...

If a "private network" or "vpn tunnel" is used, then many provider offers a quiet static IP.
If a "public internet breakout" is used, it's mainly a NAT (otherwise your device will be too frequently keep a wake by foreign traffic.)

**Comment by noomio** [comment]
Ok, I will ask our provider. Maybe they can shed some light to this.

**Comment by noomio** [comment]
Will a NON empty message work to maintain this?

**Comment by noomio** [comment]
I was able to verify that the connection is kept alive when sending RST every minute. It looks like the quite period time is 2 minutes.

**Comment by noomio** [comment]
I can confirm that this is enough to keep it happy. I sent every 2 minutes.

**Comment by boaks** [comment]
You don't even need to spend 4 bytes, others are just send a 0 or 1 byte UDP message.
The downside is more the energy, that may be required on the cellular device.

**Comment by noomio** [comment]
oh, nice I will do that.

Yeah, but what can you do if this is required to keep the devices port the same?

The device needs to be ON anyways as it shall accept calls. I can just put the MCU in deep sleep and modem in sleep for 2 min, wake up and ping.

Or just let observe expiry normally and re-observe and consume the data in the queue (this works fine now too)

In reality observe becomes kinda meeaningless in such as scenario for Iot devices due to NAT. I didnt expect this ping requirement.
