### ISSUE TITLE
coaps server failes to process client hello(Reassembled) mesage

### ISSUE THREAD

**Issue by chen0411** [eclipse-californium/californium#2123]
Hello, 
I'm having a issue，Coaps server ( Run Californium) failes to process client hello (Reassembled) mesage. What is the cause of the issue?

basic issue information
1. californium branch/release  
    2.0.0-M18

2. tcpdump captures and californim logs
[client_hello.zip](https://github.com/eclipse-californium/californium/files/11067853/client_hello.zip)

3. issue analysis
a、The client initiates a DTLS handshake message with the server. When the client sends the second client hello message, the MTU used by the client is 256. Client hello is split into two packets and sent.
![image](https://user-images.githubusercontent.com/4214773/227690301-24c0b8d6-2255-4911-b460-54f5ecb6d178.png)
Client Hello  (Fragment）
![image](https://user-images.githubusercontent.com/4214773/227690579-ef7fab14-d2ef-4940-9d8e-dea5501f2e4b.png)
Client Hello (Reassembled )
![image](https://user-images.githubusercontent.com/4214773/227690598-4d2302c5-dff5-41d0-98bb-de33cbc48361.png)

b、check californim logs
Packets are not reassembled and process failed.
![image](https://user-images.githubusercontent.com/4214773/227691519-cc2658fe-c151-4d90-ad89-8446899e41bd.png)
![image](https://user-images.githubusercontent.com/4214773/227692209-913e1015-6a7c-424f-8e4d-bef741022055.png)
![image](https://user-images.githubusercontent.com/4214773/227692268-e6c6224c-7a73-42f7-bc6a-ef9276d279f3.png)

**Comment by boaks** [comment]
You know, that the current release is 3.8.0.
We can't offer support for pretty deprecated milestone version.
For a fast interim solution, you may try to update to 2.7.4 and then start the migration to 3.8.0.

**Comment by boaks** [comment]
Just to mention:
Even the 3.8.0 is not able to process fragmented Client_Hellos. That's not implemented. if you configure your client with a useful subset of cipher suites, the Client_Hello will get much smaller.

**Comment by chen0411** [comment]
> Just to mention: Even the 3.8.0 is not able to process fragmented Client_Hellos. That's not implemented. If you configure your client with a useful subset of cipher suites, the Client_Hello will get much smaller.

Thank you for your reply
