### ISSUE TITLE
Supporting ARIA Ciphersuite

### ISSUE THREAD

**Issue by ibndias** [eclipse-californium/californium#2124]
I am using Leshan LWM2M server and Anjay as a client.

My client is already configured to use TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384 ciphersuite.

![image](https://user-images.githubusercontent.com/3958152/227764080-8c9ad6db-7d98-4c37-ba01-98f70713ff59.png)

But handshake was failed because californium does not support ARIA based ciphersuite.

I Added on CipherSuite.java
```
TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384(0xC049, CertificateKeyAlgorithm.EC, KeyExchangeAlgorithm.EC_DIFFIE_HELLMAN, CipherSpec.ARIA_256_CBC, MACAlgorithm.HMAC_SHA384, false, PRFAlgorithm.TLS_PRF_SHA384),
TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256(0xc05C, CertificateKeyAlgorithm.EC, KeyExchangeAlgorithm.EC_DIFFIE_HELLMAN, CipherSpec.ARIA_128_GCM, true),
```
But it causes error
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.15.0:check (default) on project scandium: The following API problems caused the build to fail:
[ERROR] java.field.enumConstantOrderChanged: field org.eclipse.californium.scandium.dtls.cipher.CipherSuite.TLS_EMPTY_RENEGOTIATION_INFO_SCSV: The enum constant was defined on position 27 but is now on 29. The user code can break if it relies on the return value of the "ordinal()" method. https://revapi.org/revapi-java/differences.html#java.field.enumConstantOrderChanged
[ERROR] java.field.enumConstantOrderChanged: field org.eclipse.californium.scandium.dtls.cipher.CipherSuite.TLS_NULL_WITH_NULL_NULL: The enum constant was defined on position 26 but is now on 28. The user code can break if it relies on the return value of the "ordinal()" method. https://revapi.org/revapi-java/differences.html#java.field.enumConstantOrderChanged
```

So i put it after `TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00ff),`

Then i do `mvn clean install` for californium, then for leshan. everything seems okay.

But then I try to connect, the handshake failed. From the Leshan log
```
2023-03-26 07:22:07,564 ServerHandshaker     [DEBUG] handshake started dtls-con: CID=D9615D4433CC, 36.38.155.27:54844, is alive PEER=36.38.155.27:54844, CONNECTION_ID=D9615D4433CC
2023-03-26 07:22:07,564 Connection           [DEBUG] Handshake with [36.38.155.27:54844] has been started PEER=36.38.155.27:54844, CONNECTION_ID=D9615D4433CC
2023-03-26 07:22:07,564 ServerHandshaker     [TRACE] Server cipher suites: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8, TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8, TLS_ECDHE_ECDSA_WITH_AES_128_CCM, TLS_ECDHE_ECDSA_WITH_AES_256_CCM, TLS_ECDHE_PSK_WITH_AES_128_GCM_SHA256, TLS_ECDHE_PSK_WITH_AES_256_GCM_SHA378, TLS_ECDHE_PSK_WITH_AES_128_CCM_8_SHA256, TLS_ECDHE_PSK_WITH_AES_128_CCM_SHA256, TLS_PSK_WITH_AES_128_GCM_SHA256, TLS_PSK_WITH_AES_256_GCM_SHA378, TLS_PSK_WITH_AES_128_CCM_8, TLS_PSK_WITH_AES_256_CCM_8, TLS_PSK_WITH_AES_128_CCM, TLS_PSK_WITH_AES_256_CCM] PEER=36.38.155.27:54844, CONNECTION_ID=D9615D4433CC
2023-03-26 07:22:07,565 DTLSConnector        [TRACE] Aborting handshake with peer [36.38.155.27:54844]: PEER=36.38.155.27:54844, CONNECTION_ID=D9615D4433CC
org.eclipse.californium.scandium.dtls.HandshakeException: Client does not propose a common cipher suite
```

What else do i need to modify to support aria ciphersuite? Isn't scandium already use BouncyCastle as provider?

I am using leshan 2.0.0 and californium 3.8.0.

Any help would be appreciated. Thanks

**Comment by boaks** [comment]
> What else do i need to modify to support aria ciphersuite? 

Do you plan to contribute that extension?

I'm not sure, what is missing, I guess, you even didn't show all changes you applied (e.g.  `CipherSpec.ARIA_256_CBC` seems to be missing). 

In the end it would require to debug an check, where it went wrong. The implementation doesn't consider to be extended by users.

>  Isn't scandium already use BouncyCastle as provider?

No, you may chose BouncyCastle as provider, but the default is the JCE of your JRE.
Even with BouncyCastle, Scandium only uses the "basic crypto functions", but implements DTLS 1.2 around that.

**Comment by boaks** [comment]
Just in the case, you don't plan to contribute it:

See:
- [DTLSConnectionState](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DTLSConnectionState.java)
- [DtlsBlockConnectionState](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DtlsBlockConnectionState.java)
- [DtlsAeadConnectionState](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/DtlsAeadConnectionState.java)
- [AeadBlockCipher](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/AeadBlockCipher.java)
- [CCMBlockCipher](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CCMBlockCipher.java)
- [CbcBlockCipher](https://github.com/eclipse-californium/californium/blob/main/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/CbcBlockCipher.java)

are involved. 

**Note:** if you modify such code without contributing it, you may need to spend also time in the future to maintain that with other changes/update in Scandium.

**Comment by ibndias** [comment]
> Do you plan to contribute that extension?

Sure I will try if it works.

Sorry, forgot to put my CipherSpec:

```
ARIA_256_CBC("ARIA/CBC/NoPadding", CipherType.BLOCK, 32, 0, 16),
ARIA_128_GCM("ARIA/GCM/NoPadding", CipherType.AEAD, 16, 4, 8, 16),
```
The BouncyCastle already has this block cipher.

I also tried to change the provider by changing `CALIFORNIUM_JCE_PROVIDER ` to `"BC"` in `JceNames.java`
```
/**
	 * Name of environment variable to specify the JCE.
	 */
	public String CALIFORNIUM_JCE_PROVIDER = "BC";//"CALIFORNIUM_JCE_PROVIDER";
```
But i got this error
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.15.0:check (default) on project element-connector: The following API problems caused the build to fail:
[ERROR] java.field.constantValueChanged: field org.eclipse.californium.elements.util.JceNames.CALIFORNIUM_JCE_PROVIDER: Constant field changed value from 'CALIFORNIUM_JCE_PROVIDER' to 'BC'. https://revapi.org/revapi-java/differences.html#java.field.constantValueChanged
```
I am not familiar with java, I don't understand why changing the constant returns error

**Comment by boaks** [comment]
"revapi" is a tool to ensure, that a newer version of a java library can be used without compiling the new stuff again.

E.g. a "final" field may be used at compile time in your code. if you change that "final" field in the library, this doesn't work without compiling your own code also.

```
public String CALIFORNIUM_JCE_PROVIDER = "BC";//"CALIFORNIUM_JCE_PROVIDER";
```

Which java version are you plan to use? Maybe the newer java versions also support ARIA (I haven't checked that). Then you would not need to setup Californium to use BouncyCastle. 

> I am not familiar with java, 

It's not too easy to use BC. It requires a lot knowledge about jars and how to configure and start java.
To enable BC, you need to put the BC libraries in the classpath and  set either a OS environment variable or a java-property using the name "CALIFORNIUM_JCE_PROVIDER" and provide "BC" (or "BC_NON_BLOCKING_RANDOM"). 

I only tested BC using maven to execute the tests, therefore I have no detailed instructions how to do that on the CLI.
 
> The BouncyCastle already has this block cipher.

Yes, but usually using such a "block cipher" for (D)TLS comes with some more details and parameters, which are considered in the above classes. And these classes are not designed to be easily extended for newer cipher suites.
Therefore you need to do more.

**Comment by boaks** [comment]
I added the `CipherSpec` and `CipherSuite` and a interoperability test with openssl 3.2 and BouncyCastle 1.72 the "TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256" works without additional changes!

(AFAIK, the "TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384" isn't support by openssl.)

I think, it's required to document how to use BouncyCastle in order to enable users to easier benefit from it.

Openjdk 17 seems not to support ARIA, at least not as `Cipher`.

**Comment by boaks** [comment]
Just as first hint, it will take some time to be able to spend time into a more detailed documentation:

1. specify the JCE provider using "CALIFORNIUM_JCE_PROVIDER" either as environment variable or java property.
2. add the bouncy castle libraries to your classpath.

For unix, that may work with

```
export CALIFORNIUM_JCE_PROVIDER=BC
...
java ...
```

or 

```
java  -DCALIFORNIUM_JCE_PROVIDER=BC ... 
```

For DTLS 1.2, the `bcprov-jdk18on` and `bcutil-jdk18on` jars are required to be added to the classpath for java 8 or newer.

**Comment by ibndias** [comment]
Thank you! The TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 cipher suite works perfectly on Leshan using 
```
java  -DCALIFORNIUM_JCE_PROVIDER=BC ... `
```
![image](https://user-images.githubusercontent.com/3958152/227787388-743c84ee-8501-4b89-b003-813afc5b2052.png)

> For DTLS 1.2, the bcprov-jdk18on and bcutil-jdk18on jars are required to be added to the classpath for java 8 or newer.

Seems like I missed the error log from Leshan. The californium failed to load the BouncyCastle via classpath, maybe it's just me using it wrong but it was solved by adding via dependency in `element-connector/pom.xml`

```
<dependency>
<groupId>org.bouncycastle</groupId>
<artifactId>bcprov-jdk18on</artifactId>
<version>1.72</version>
</dependency>
<dependency>
<groupId>org.bouncycastle</groupId>
<artifactId>bctls-jdk18on</artifactId>
<version>1.72</version>
</dependency>
```

I think I'm not ready to contribute yet, but thanks for your help!

**Comment by boaks** [comment]
> I think I'm not ready to contribute yet, but thanks for your help!

Though it seems to require only to add the cipher-suite enums, I will add it on my own.
I currently try to disable the enum check in revapi, if that's done, I will prepare a PR.

**Comment by boaks** [comment]
See PR #2125
