### ISSUE TITLE
Observe and piggyback response

### ISSUE THREAD

**Issue by noomio** [eclipse-californium/californium#2126]
Hi,

Is it possible for an observe to reply with data instead of only ACK?

I had a try but it seems like it forces the observe relation ship to end.

**Comment by boaks** [comment]
> Is it possible for an observe to reply with data instead of only ACK?

There are two cases:
- the client observe request
- the server notification response

For the client observe request both, piggybacked or separate responses are possible, and should work. In both cases the response must use the observe option, if the observe relation is established. That is somehow considered to be the initial response.

For the server notifications (follow up responses) either NON or CON responses are used. And for a CON response the client needs to ACK the transmission. That uses naturally the "separate response" pattern.

Without wireshark capture it's always not too easy to say, if it's valid or not.

**Comment by noomio** [comment]
Hi,

Here is the CON from the server with some content data:

![image](https://user-images.githubusercontent.com/51944940/228165291-d80c26f2-3ed6-4924-a256-4224f8f3c876.png)

This is then the ACK with some Content in the reply:

![image](https://user-images.githubusercontent.com/51944940/228165489-9aea2f33-ad91-4306-8e95-33708fb929f7.png)

As you can see the server doesnt accept the ACK and tries to resend the data and eventually stop and removes the observe relationship

**Comment by noomio** [comment]
This is a corrected reply without the options but still the observe relationship is removed.

![image](https://user-images.githubusercontent.com/51944940/228168669-a9447ec4-ba4c-4754-9a3f-28d1b59f3238.png)

**Comment by boaks** [comment]
Did you read

[IP Capturing](https://github.com/eclipse-californium/californium/wiki/Logs-and-IP-Capturing-%E2%80%90-How-To-Provide-The-Right-Information#ip-capturing-tools---unix-ubuntu-1804)

:exclamation::exclamation::exclamation: Provide NO SCREENSHOTS, the capture files are required :exclamation::exclamation::exclamation:

?
The screenshot doesn't contain all the details, that makes it hard to see the root-cause.

What I see:
- the coap-clients observe request is ACKed and then a CON response is send (separate response).
- the coap-clients sends a "ACK" for the CON response, but that's obvious a "piggybacked response". That violates RFC7252. You may ACK/respond to an request, but for a CON response, you must use real (empty) ACK.

Please read RFC7252 carefully. There is a transmission layer with NON, CON, ACK and RST, that uses a MID for matching. And a application request/response layer with "request and response codes", which uses the token for matching. And there is one mix-case, where both layers are "combined" together, that's the piggybacked response.

[RFC7252 4.3](https://www.rfc-editor.org/rfc/rfc7252#section-4.3)  Table 1: Usage of Message Types
 
[RFC7252 5.2](https://www.rfc-editor.org/rfc/rfc7252#section-5.2) Figure 9: Structure of a Response Code
 
A empty message (ACK/RST) has always code 0.
A request has class code (highest 3 bits) of 0.
A response has class code (highest 3 bits) of 2, 4, or 5.

The combination of the two tables results in the valid messages.
You can't send a ACK 2.05 response as ACK for a CON 2.0r response (notify).

**Comment by noomio** [comment]
Hi,

Sorry about the attachement, did it in a hurry  :( 

Prior to this piggy back response I acked correctly and there arent any issues. I read the RFC but wasnt sure if this was possible hence asking.

Thank you for you time and I appreciate you time responding.
