### ISSUE TITLE
Missing coap max ack timeout in Coapconfig.java applydefinitions

### ISSUE THREAD

**Issue by sathysreenath** [eclipse-californium/californium#2127]
It looks like the coap max ack timeout parameter is missing from this file, hence when we generate the californium properties we do not see this parameter as well. So we cannot adjust the max ack timeout to a value other than 60 seconds. I see that the max ack timeout is declared as public static param in the file.

https://github.com/eclipse-californium/californium/blob/e927def9c72d062d750cc7dca441afc1f5b33fd7/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L794-L852

public void applyDefinitions(Configuration config) {...}

I see a ack timeout but no max ack timeout.

**Comment by boaks** [comment]
Yes good catch, I will add it.

**Comment by sbernard31** [comment]
Just by curiosity,  is there plan to release a new version with this fix ?

**Comment by boaks** [comment]
I'm busy with other jobs, but I will try that for Thursday 20.07.2023.

**Comment by boaks** [comment]
> So don't release because of this question.

No, not just because of the question.
I had that in mind, but I'm currently on something else. The 20.07.2023 should be OK for me.
AFAIK, there may be some OSCORE bugfixes pending, but I'm not sure, what's the schedule there.

**Comment by boaks** [comment]
> On your side, this is still not something you plan to work on ?

I currently spend my most time into cellular apps and plan to spend time into the CoAP-S3-proxy afterwards.
I don't plan to spend time in OSCORE, DTLS 1.3, execution- or config-redesign.
The "goal" from my side is somethings as spending "1 afternoon per week" into Californium and tinydtls. 

Beside of Julian's request, it's hard to see, if someone else is really interested in changes.
At least, I don't see someone, who is willing to spend time in that.
