### ISSUE TITLE
Non-confirmable Message Problem

### ISSUE THREAD

**Issue by KeithLaiKB** [eclipse-californium/californium#2129]
Case:
I found that when I applied Non-confirmable Resources, and the client observes the resource.

Problem:
When the client receives the 100th message or each 100 message, why the message is a confirmable message?

Is it a feature? How could I configure this number(100)? 
And I could not find a related reference to this phenomenon in CoAP reference.
Could you please help me?

**Comment by boaks** [comment]
> Is it a feature?

Yes, [RFC 7641 - 4.5. Transmission](https://www.rfc-editor.org/rfc/rfc7641#section-4.5) (at the end):

```
A server that transmits notifications mostly in non-confirmable
messages MUST send a notification in a confirmable message instead of
a non-confirmable message at least every 24 hours.  This prevents a
client that went away or is no longer interested from remaining in
the list of observers indefinitely.
```

> How could I configure this number(100)?

As of the very most CoAP configuration, see [CoapConfig](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L637-L675)

>And I could not find a related reference to this phenomenon in CoAP reference.

In which CoAP reference did you search?

**Comment by KeithLaiKB** [comment]
> As of the very most CoAP configuration, see [CoapConfig](https://github.com/eclipse-californium/californium/blob/main/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L637-L675)

Is it the NOTIFICATION_CHECK_INTERVAL_COUNT?

**Comment by boaks** [comment]
> Is it the NOTIFICATION_CHECK_INTERVAL_COUNT?

That depends on your precise question. I guess, for now yes.
After a few minutes your question may change and then the answer will be no.
So, maybe you start to read the RFC 7641 and the documentation of these configuration values.

**Comment by KeithLaiKB** [comment]
when I search the variable, I could not find a demo for this configuration, is it configured in CoapResource or server, or client?

**Comment by boaks** [comment]
> I could not find a demo for this configuration

There is no special demo for this configuration, because it belongs to the common [Configuration](https://github.com/eclipse-californium/californium/blob/main/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java).

I guess, in your case, editing the "Californium.properties" should be a possible way.

```
# Interval time to check notifications receiver using a CON message.
# Default: 2[min]
COAP.NOTIFICATION_CHECK_INTERVAL=2[min]
# Interval counter to check notifications receiver using a CON message.
# Default: 100
COAP.NOTIFICATION_CHECK_INTERVAL_COUNT=100
# Additional time (backoff) to the max-age option
# for waiting for the next notification before reregister.
# Default: 2[s]
COAP.NOTIFICATION_REREGISTRATION_BACKOFF=2[s]
```

But again, if you don't provide the information, what and how you currently use Californium, I can only provide some general answers, which may or may not match your case.

**Comment by boaks** [comment]
> Shouldn't that be [Californium3.properties](https://github.com/eclipse-californium/californium/blob/261defe6cedb75610ee53fcb190789c6fa4a6d3f/element-connector/src/main/java/org/eclipse/californium/elements/config/Configuration.java#LL196C5-L196C5) ? (Assuming the latest release of Californium)

Yes, typo.

**Comment by boaks** [comment]
Have you been successful with changing the notifications?
Any left question according the "CON notify" to verify the client's interest?
If not, can we close this issue?

**Comment by boaks** [comment]
Don't hesitate to comment again on this issue or open a new one, if you have further questions.
