### ISSUE TITLE
Alert should be BAD_CERTIFICATE instead of DECRYPT_ERROR when certificate chain can't be validated

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [eclipse-californium/californium#2132]
https://github.com/eclipse-californium/californium/blob/95531fe0aa746f4f9922f1e7444ee46241c50e0c/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/x509/StaticNewAdvancedCertificateVerifier.java#L226

The alert here should be  BAD_CERTIFICATE instead of DECRYPT_ERROR. 

Sorry for not being able to provide a pr because of the secuirty policy of my campany.

**Comment by boaks** [comment]
Thanks for reporting.

[RFC5246](https://www.rfc-editor.org/rfc/rfc5246#page-31)

> bad_certificate
>        A certificate was corrupt, contained signatures that did not
>        verify correctly, etc.

and

> decrypt_error
>        A handshake cryptographic operation failed, including being unable
>        to correctly verify a signature or validate a Finished message.
>        This message is always fatal.

FMPOV, the causing `GeneralSecurityException` is unspecific, so it's to decide, which one matches better.
Without the actual cause and/or the invalid message, it's hard to improve the code without violate other cases.
Anyway, I have no real strong opinion on that. Do you have additional infos as the exception message or a hint, what's wrong on the certificate messageß

**Comment by Nick-The-Uncharted** [comment]
@boaks But it's not consistent with other implentation of `org.eclipse.leshan.client.californium.BaseCertificateVerifier#verifyCertificate`.
ServiceCertificateConstraintCertificateVerifier/CaConstraintCertificateVerifier/ServiceCertificateConstraintCertificateVerifier all used BAD_CERTIFICATE. Certificate message is not encrypted, so maybe bad_certificate is more appropricate.

**Comment by boaks** [comment]
> org.eclipse.leshan

leshan != californium

Are you faced such exceptions? If so, what's the exception message? 
Or is this a question in advance, in order to have the same behavior for the leshan verifier and the californium one?

**Comment by boaks** [comment]
Please check, if PR #2133 works for you.

**Comment by Nick-The-Uncharted** [comment]
@boaks Sorry for the delay, I confirmed that the exception I faced is `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found` (I misconfigured trust ca). So your pr perfectly solved my problem.

**Comment by Nick-The-Uncharted** [comment]
@boaks That's better, that makes identifying tls failure much easier.
