### ISSUE TITLE
COAP block Transfer fails at block 0xFFFF

### ISSUE THREAD

**Issue by AlexBHQ** [eclipse-californium/californium#2141]
Hi 
Firmware transfer fails repeatedly when client requests block 0xFFFF in PULL mode.

Californium server is used with ioterop client. 
Californium server version: 3.8.0

the .pcap file was refused, but the error is very well detailed in the screen shot below.
4 last messages:
![TransferFail](https://github.com/eclipse-californium/californium/assets/136717754/d7c11169-fe2d-4700-973d-96a35e68456b)

The client fails with:
[warning:coap:blockHandleMessage:724] Out of order block. Expected #65535, received #0.
[warning:coap:prv_resultCallback:115] Download failed.

Cordially,

**Comment by jvermillard** [comment]
Are you sure that the client support 64k blocks? it's quite a lot (~67MBytes).
Without, at minimum the full dump of the packet or at least a screenshot on how Wireshark decode them
If you want to know how Cf is decoding the blockwise option you can look at the BlockOptionTest.java in the core test; for me large num values are covered.

**Comment by AlexBHQ** [comment]
Hi J, 
You are right, the file is quite large (75MB) and yes the client support more than 64k block. (the full 20 bits specified in RFC).
The screenshots of the wireshark is there, so you should be abled to see it. 
I looked at the blockOption code and it looks good, but something hapens between the requested block (0xFFFF) and the delivered block (0x0) as shown on the image. Could it be another limit elsewhere?

**Comment by boaks** [comment]
Could you please check, if that happens, when you set:

COAP.DEDUPLICATOR=PEERS_MARK_AND_SWEEP

If that solves the issue, it seems more to be an MID overflow.

**Comment by AlexBHQ** [comment]
Hi Boaks, 

Thank you for the suggestion.
we set the config.set(CoapConfig.DEDUPLICATOR, CoapConfig.DEDUPLICATOR_PEERS_MARK_AND_SWEEP); option, but the result was the same. 

Sorry for the pcap, here is the gzip.
[LastPackets.pcap.gz](https://github.com/eclipse-californium/californium/files/11762351/LastPackets.pcap.gz)

**Comment by AlexBHQ** [comment]
Oh, I just realized the last GET is flagged as a retransmission. 
I will try a shorter CAOP.EXCHANGE_LIFETIME.

**Comment by AlexBHQ** [comment]
Thank you for the support, 

Boaks was right. 
COAP.DEDUPLICATOR=PEERS_MARK_AND_SWEEP actually did the trick, my initial test was invalid. 

Cordially,
