### ISSUE TITLE
Confirmable message with ACK with next message

### ISSUE THREAD

**Issue by KeithLaiKB** [eclipse-californium/californium#2152]
In Confirmable message, with observer pattern: 
When the server does not receive the ACK from the client about **messageA**, will the server keep sending the second message **messageB** to the client? It seems like there is no reference mentioned that clearly.

**Comment by boaks** [comment]
Please read [RFC7641 - 4.5.2 Advanced Transmission](https://www.rfc-editor.org/rfc/rfc7641.html#section-4.5.2).  

Let me recommend, that you study RFC7641 in complete, I guess this will answer a lot of your questions.
And I still don't know, what's the use-case you want to optimize in your other issue #2129.

**Comment by KeithLaiKB** [comment]
> Please read [RFC7641 - 4.5.2 Advanced Transmission](https://www.rfc-editor.org/rfc/rfc7641.html#section-4.5.2).
> 
> Let me recommend, that you study RFC7641 completely, I guess this will answer a lot of your questions. And I still don't know, what's the use-case you want to optimize in your other issue #2129.

Thank you, and #2129 is ok right now

**Comment by boaks** [comment]
> For this purpose, the server MAY optimize the transmission process by
>    aborting the transmission of the old notification (but not before the
>    current transmission attempt is completed) and starting a new
>    transmission for the new notification (but with the retransmission
>    timer and counter of the aborted transmission retained).

That is followed by more details in 4 topics. 

If notification **message A** is CON and not ACKed, Californium will resend that notification on transmission timeout, as usual for an CON transfer. If within this  transmission timeout the resource changes again, Californium will withdraw the **message A** and replace it with **message B** using the current transmission counter and timer before sending it.

**Comment by KeithLaiKB** [comment]
> 

So, in short, could we say that whether the server has received the PUBACK within the timeout or out of the timeout period, once the message content changes, the new message will send to the client without waiting anymore, right?

**Comment by KeithLaiKB** [comment]
> > For this purpose, the server MAY optimize the transmission process by
> > aborting the transmission of the old notification (but not before the
> > current transmission attempt is completed) and starting a new
> > transmission for the new notification (but with the retransmission
> > timer and counter of the aborted transmission retained).
> 
> That is followed by more details in 4 topics.
> 
> If notification **message A** is CON and not ACKed, Californium will resend that notification on transmission timeout, as usual for any CON transfer. If within this transmission timeout the resource changes again, Californium will withdraw the **message A** and replace it with **message B** using the current transmission counter and timer before sending it. Even if **message B** use NON, Californium will switch that to CON when replacing the previous CON message. This only applies for notifications.

So, in short, could we say that whether the server has received the PUBACK within the timeout or out of the timeout period, once the message content changes, the new message will send to the client without waiting anymore, right?

**Comment by boaks** [comment]
> the new message will send to the client without waiting anymore, right?

No. 
The server waits for the timeout and send the new notification instead of the retransmission.

There are two mechanisms, which cooperate:
- CON transmission with congestion control, therefore exponential retransmission timeout.
- Observer/notify: try to send the freshest state to the client

The first must be obeyed, therefore a fresher notification can only be send, when either a ACK is received or the timeout is reached. When sending the fresh notification, the transmission counter and timeout are not reseted.

E.g.:

| time | #notification | send | #retransmission | timeout |
| - | - | - | - | - |
| 00.000 | 1 | y | 0 | 2s |
| 02.000 | 1 | y | 1 | 4s |
| 03.000 | 2 | n | - | - |
| 06.000 | 2 | y | 2 | 8s |

**Comment by KeithLaiKB** [comment]
> > the new message will send to the client without waiting anymore, right?
> 
> No. The server waits for the timeout and send the new notification instead of the retransmission.
> 
> There are two mechanisms, which cooperate:
> 
> * CON transmission with congestion control, therefore exponential retransmission timeout.
> * Observer/notify: try to send the freshest state to the client
> 
> The first must be obeyed, therefore a fresher notification can only be send, when either a ACK is received or the timeout is reached. When sending the fresh notification, the transmission counter and timeout are not reseted.
> 
> E.g.:
> 
> time	#notification	send	#retransmission	timeout
> 00.000	1	y	0	2s
> 02.000	1	y	1	4s
> 03.000	2	n	-	-
> 06.000	2	y	2	8s

but I tried to shutdown the coapclient immediately, but I use wireshark to capture that server could still send the next message, even though this message could not be reach to client side.

**Comment by boaks** [comment]
> but I tried to shutdown the coapclient immediately, 

OK

> but I use wireshark to capture 

but you didn't provide the captures

> that server could still send the next message, even though this message could not be reach to client side.

If the message could not reach the client, the client will not ACK.
In consequence, the server will (re-)send the current notification.
Or, if the resource has changed and a new notification is available,
that new notification is send instead. That's what RFC7641 4.5.2 defines.

**Comment by KeithLaiKB** [comment]
> > but I tried to shutdown the coapclient immediately,
> 
> OK
> 
> > but I use wireshark to capture
> 
> but you didn't provide the captures
> 
> > that server could still send the next message, even though this message could not be reach to client side.
> 
> If the message could not reach the client, the client will not ACK. In consequence, the server will (re-)send the current notification. Or, if the resource has changed and a new notification is available, that new notification is send instead. That's what RFC7641 4.5.2 defines.

No.	Time	Source	Destination	Protocol	Length	Info
211	55.110546059	192.168.50.248	192.168.50.55	CoAP	46	ACK, MID:17672, Empty Message
212	55.606328763	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17673, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
213	55.610161300	192.168.50.248	192.168.50.55	CoAP	46	ACK, MID:17673, Empty Message
214	56.106836244	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17674, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
215	56.110940040	192.168.50.248	192.168.50.55	CoAP	46	ACK, MID:17674, Empty Message
216	56.606369725	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17675, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
217	56.608853669	192.168.50.248	192.168.50.55	ICMP	96	Destination unreachable (Port unreachable)
218	58.920620427	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17676, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
219	58.984714872	192.168.50.248	192.168.50.55	ICMP	96	Destination unreachable (Port unreachable)
220	59.871051279	192.168.50.1	224.0.0.1	IGMPv3	50	Membership Query, general
221	59.871157242	192.168.50.1	224.0.0.1	IGMPv3	50	Membership Query, general
222	60.706673111	e4:5f:01:9c:d4:3a	e4:5f:01:9c:d3:bf	ARP	60	Who has 192.168.50.55? Tell 192.168.50.248
223	60.706725352	e4:5f:01:9c:d3:bf	e4:5f:01:9c:d4:3a	ARP	42	192.168.50.55 is at e4:5f:01:9c:d3:bf
224	63.537773832	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17677, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
225	63.592474962	192.168.50.248	192.168.50.55	ICMP	96	Destination unreachable (Port unreachable)
226	66.979347015	192.168.50.55	224.0.0.22	IGMPv3	54	Membership Report / Join group 224.0.0.251 for any sources
227	72.770816901	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17678, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
228	72.808918197	192.168.50.248	192.168.50.55	ICMP	96	Destination unreachable (Port unreachable)
229	80.180868433	192.168.50.1	224.0.0.1	IGMPv3	50	Membership Query, general
230	80.181079915	192.168.50.1	224.0.0.1	IGMPv3	50	Membership Query, general
231	90.019345168	192.168.50.55	224.0.0.22	IGMPv3	54	Membership Report / Join group 224.0.0.251 for any sources
232	91.236448760	192.168.50.55	192.168.50.248	CoAP	68	CON, MID:17679, 2.05 Content (text/plain), TKN:e9 9b 2f 3c 2b 1f 1d 48, /Resource1
233	91.646160019	192.168.50.248	192.168.50.55	ICMP	96	Destination unreachable (Port unreachable)

**Comment by boaks** [comment]
> as you can see, after 216 packet, there is no ack, but it was still sending the message, and in the message, my content is different, if you want I can put it here.

Yes, and that's what I'm writing.

**Comment by KeithLaiKB** [comment]
![image](https://github.com/eclipse-californium/californium/assets/18576178/ea8757f8-9d7c-4726-9614-fdc346cfaab6)
![image](https://github.com/eclipse-californium/californium/assets/18576178/ce6eef64-e0c8-4dc6-b900-eff0ffa8c2c4)
![image](https://github.com/eclipse-californium/californium/assets/18576178/0957c502-894b-427e-bda4-f5b5276e4007)
![image](https://github.com/eclipse-californium/californium/assets/18576178/3e0cfa7e-6872-45ba-8a71-d58ec978c459)


> > as you can see, after 216 packet, there is no ack, but it was still sending the message, and in the message, my content is different, if you want I can put it here.
> 
> Yes, and that's what I'm writing.

**Comment by boaks** [comment]
No pictures! You don't read the links, don't you?

The behavior of Californium is according the RFC. I'm not sure, what you want to discuss.

**Comment by KeithLaiKB** [comment]
> No pictures! You don't read the links, don't you?
> 
> The behavior of Californium is according the RFC. I'm not sure, what you want to discuss.

sorry,
so I mean in observer pattern, whatever the timeout period, if there is new content, the next message will still send to the client even though the server did not receive the ack of the message before.

**Comment by boaks** [comment]
Sorry, I don't get it.

**Comment by boaks** [comment]
I've retested it. 
As  I assumed and wrote, Californium complies with RFC7252/TFC7641

[observe.pcapng.gz](https://github.com/eclipse-californium/californium/files/11925230/observe.pcapng.gz)

This shows.
Californium sends the CON messages using retransmission with a backoff strategy.
The initial transmission timeout is about 2s, the backoff is x2.
The notifies are changing every second.

Up to sample 10, all is well. The notifies are send with an interval of 1s and are all ACKed.
Starting with 11, the client is offline. Therefore the COM notify is not ACKed.
The transmission timer times out 2s later (as the initial timer value) and 12 is a retransmission at that time.
Though the resource has changed, the new content is sent with a new MID.
Also the retransmission counter is incremented and the timeout is doubled to 4s. 
And so on, until the retransmission counter reaches the maximum and the observe registration is removed on that final timeout.

I'm still not sure, what you want to report. As you see here, it requires a lot of information to see, if the behavior is well. 

Hope this help to understand the retransmission (RFC 7252) and notify replacement  (RFC 7641).
