### ISSUE TITLE
DatagramFilterExtended#onDrop called with not "full" Record

### ISSUE THREAD

**Issue by Wisien999** [eclipse-californium/californium#2171]
I noticed there is a [case](https://github.com/eclipse-californium/californium/blob/bf1bf79452cc5fffed1cfb24044a29f48df18655/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L2091C13-L2091C13) where `org.eclipse.californium.scandium.DatagramFilterExtended#onDrop(org.eclipse.californium.scandium.dtls.Record)` is called with `peerAddress` set to null. It can cause some problems (It did in my organization). Seems like this is the only such situation. Would it be possible to add `firstRecord.setAddress(peerAddress, router)` one line above? I should solve the issue.
Also as I would consider it a bug is it possible to release this fix quickly with patch version change?

**Comment by boaks** [comment]
I'm on the bugfix. 
If successful, I schedule a bugfix release 3.9.1 for Thursday.

**Comment by boaks** [comment]
If possible, please verify the bugfix.

**Comment by Wisien999** [comment]
Sorry for the late response. That's exactly what I meant. Should work. Thank you.

**Comment by boaks** [comment]
OK, then I schedule a Bugfix Release 3.9.1 for next Thursday.

**Comment by boaks** [comment]
See #2181
