### ISSUE TITLE
How to listen observe relation lifecycle ?

### ISSUE THREAD

**Issue by sbernard31** [eclipse-californium/californium#2221]
About cf 3.x, To implement LWM2M write attributes at client side, I need to alter default coap observe behavior at coap server side . 

I almost succeed to get a working version. (even if I don't really like the code I written in Leshan :disappointed:)
Anyway, to do that I have kind of store which hold some data  for each relation for each relation. Those data contain how the behavior is altered.

**The last (known) remaining problem:** 
My current issue is I don't find a right way to do housekeeping of those data.
Ideally I should be able to remove my data when observe relation is removed too.

Any Idea ?

**Comment by sbernard31** [comment]
As I didn't find a way to listen observe relation lifecycle, I fallback to a not Ideal solution by hooking some housekeeping code in several places. I tried to hook to all the cases which could lead to end an observe relation at coap server (RST on notification, notification with error code, receive observe with observe option =1).  Hoping I didn't missed an existing one OR new one will not be added. 

Anyway, If you have better idea, please let me know.

**Comment by sbernard31** [comment]
Thx for sharing that. I totally missed this API. 

I tired to use it and it seems it works for my need. (at least is OK with my unit tests)

> Not sure, if that has a chance to work on removing the resource itself.

I didn't test that for now. 

I think we can close this issue ?

**Comment by boaks** [comment]
> I think we can close this issue ?

At  least for v 3.x.y
