### ISSUE TITLE
OSCORE setRecipientSeq() is not visible

### ISSUE THREAD

**Issue by davidecontinanza** [eclipse-californium/californium#2222]
Version: 3.10.0

Example: the Californium server starts and loads an OSCORE security context (OSCoreCtx) for a client, an IoT device. 
The client start communicating and after a while its sequence number is 1000.
The server reboots, and it reload the security context for the client but there is no way to update the recipient replay window, because setRecipientSeq() is not visible. So the server will accept any sequence number.
Then the client sends the sequence number 1001 and at this point the server updates the lowest_recipient_seq for the recipient context. 
But before that any attacker could have sent a replay attack with any sequence number between 1 and 1000.

**Comment by boaks** [comment]
@rikard-sics 

Any thoughts about that requested change?

**Comment by boaks** [comment]
I guess this would be in general a support for "graceful restart" for OSCORE as implemented for DTLS.
Not sure, what that will require in "cf-oscore".

**Comment by rikard-sics** [comment]
The OSCORE RFC has a section detailing safe operations if parts of the OSCORE security context (such as the Replay Window) has been lost:
https://datatracker.ietf.org/doc/html/rfc8613#section-7.5

Option 2 takes advantage of the [Appendix B.2](https://datatracker.ietf.org/doc/html/rfc8613#appendix-B.2) procedure and is implemented in the current code and can be used to continue operations safely after one peer has restarted. I can provide further details on how to use it if that can be useful.

Option 1 points to [Appendix B.1](https://datatracker.ietf.org/doc/html/rfc8613#appendix-B.1) which details an example of a procedure that relies on saving parts of the security context periodically. After a peer restarts that information can be used for safe resumption, possibly together with use of the Echo option.

Making setRecipientSeq() visible does make sense to me as that will enable implementing a procedure such as the one detailed in Appendix B.1 on the server side.

**Comment by davidecontinanza** [comment]
Thanks @rikard-sics for the comment. While Appendix B.1 describes the best procedure, having setRecipientSeq() visible could also allow to reload the security contexts on the server side without any operations on the client side (Echo). In some application this could be crucial, imagine having to force thousands of battery powered IoT devices to make unnecessary transmissions each time the server reboots. This would encourage the server administrators to do as little maintenance as possibile in order to avoid reboot at any cost.

**Comment by boaks** [comment]
Therefore

> Making setRecipientSeq() visible does make sense to me

@rikard-sics 

Do you have any pending changes for cf-oscore? 
Otherwise I will just change the visibility to `public`.

**Comment by rikard-sics** [comment]
> Therefore
> 
> > Making setRecipientSeq() visible does make sense to me
> 
> @rikard-sics
> 
> Do you have any pending changes for cf-oscore? Otherwise I will just change the visibility to `public`.

Sounds good to me. I have some things noted as TODOs, but those things are more long-term.

**Comment by boaks** [comment]
> I have some things noted as TODOs, but those things are more long-term.

I remember the bug in [outer-blockwise](https://github.com/eclipse-californium/californium/blob/main/cf-oscore/src/test/java/org/eclipse/californium/oscore/OSCoreOuterBlockwiseTest.java#L309-L350) detected in summer 2023 (changing the method for the follow on requests).

Are there any plans to fix it? Or should we put that on "known limitations"?

**Comment by rikard-sics** [comment]
> Are there any plans to fix it? Or should we put that on "known limitations"?

For sure I have a plan to fix it. I'm just not sure when I will have the time available to look into it. Ideally I would be able to fix it before summer.
