### ISSUE TITLE
Question about Key ID Context CBOR coding in OSCORE

### ISSUE THREAD

**Issue by JaroslawLegierski** [eclipse-californium/californium#2251]
During tests of OSCORE  Appendix B.2 procedure I found following issue:

When Client sends register to the server including not null Key ID Context  (e.g. 485bdeb4ba6e8b4d4b) OSCORE protected packets cannot be decoded by Wireshark
 
![image1](https://github.com/eclipse-californium/californium/assets/13430617/cc55c361-7081-44ae-ba80-20b4e2b722e5)

When I omit the function encodeToCborBstrBytes in the ContextRederivation class (modification in line 120) 
``` newCtx.setIncludeContextId(encodeToCborBstrBytes(contextID1));```
to
```newCtx.setIncludeContextId(contextID1);```
 Wireshark can decode the entire OSCORE message without any problems.
![image2](https://github.com/eclipse-californium/californium/assets/13430617/198e6ee8-0862-4b40-9d4b-ade04d2725f2)

After deeper analysis, I suspect that the problem may be the first byte (e.g. 48 in 485bdeb4ba6e8b4d4b) because the encodeToCborBstrBytes function encodes CBOR with adding the length of the Key ID Context. 
The question is whether or not the Key ID Context should be encoded in CBOR with it length added ?

**Comment by boaks** [comment]
Hi @rikard-sics 

if possible, please have a look on this.

**Comment by rikard-sics** [comment]
My understanding from the OSCORE RFC is that the ID Context values (nonces) in the Appendix B.2 procedure should indeed be placed in the OSCORE CoAP option wrapped as CBOR byte strings:

https://datatracker.ietf.org/doc/html/rfc8613#page-71
> containing R1 wrapped in a CBOR bstr as 'kid context'

The CBOR byte strings would have a CBOR header including the length and type of the following value.

I have successfully performed interop tests of the Appendix B.2 procedure with the _libcoap_ implementation. It is unfortunate that Wireshark cannot decode this, I suspect it simply does not support the Appendix B.2 procedure logic. Perhaps this is something that can be added to Wireshark (although it may be difficult to understand that Appendix B.2 is being executed between two peers).

Thanks for your question and interest in this!
