### ISSUE TITLE
cf-server certificate doesn't match

### ISSUE THREAD

**Issue by sakphea** [eclipse-californium/californium#2254]
Hi, I am implementing CoAP over DTLS based on Californium released 3.11.0. Everything is working fine Based on the secured client/server example. The challenge is that when I let the client connect to a specific IP address of the server rather than the loopback address "127.0.0.1", the handshake process fails at the certificate verification stage with this error message [ClientHandshaker]: Start certificate verification. Error occurred while sending request: java.io.IOException: org.eclipse.californium.scandium.dtls.HandshakeException: Certificate cf-server: Literal IP x.x.x.x doesn't match!]

Can you please advise me on this issue?

**Comment by sakphea** [comment]
Thanks for your swift response. I managed to get the first option working right now. I will look at the second option in due course. 
Thank you very much.

**Comment by sakphea** [comment]
I am now using SecureServer and SecureClient under cf-secure module inside demo-apps. I will let know once I can generate x509 certificate later on. 

For the time being, can you please give me a bit of guidance on how to start to implement OSCORE as I find it a bit tricky to start with unlike CoAP over DTLS which gives me a good example to start with.

Thank you in advance.

**Comment by boaks** [comment]
Unfortunately, I'm not common with OSCORE.

There are some samples in the [cf-oscore / tests](https://github.com/eclipse-californium/californium/tree/main/cf-oscore/src/test/java/org/eclipse/californium/oscore) and the plugtest-server and -client also contains some samples.

**Comment by sakphea** [comment]
Hi, I managed to get the x509 certificate on the server side working now. The sample of cf-oscore/test pointed out by you is a good point to start for OSCORE. Thank you so much.

**Comment by boaks** [comment]
You're welcome.
