### ISSUE TITLE
Remove/deprecate crop rotation deduplication algorithm

### ISSUE THREAD

**Issue by jvermillard** [eclipse-californium/californium#2300]
After some testing, I don't see a case where the crop rotation de-duplicator is better compared to the mark and sweep default algorithm. Also the documentation is quite sparse, but states "This deduplicator is probably inferior to the {@link SweepDeduplicator}." and doesn't state when it could be useful.

Since the low (no?) number of issue about this specific dedup algorithm, I think it's not really used. So I propose we deprecate/delete it

**Comment by boaks** [comment]
I agree. I guess it's a left over from the very begin. I also don't use it.

**Comment by boaks** [comment]
Removed in branch main / 4.0.x
